### ISSUE TITLE
No module named 'clip'

### ISSUE THREAD

**Issue by Nico53425342** [ZaneA/ComfyUI-ImageReward#1]
Traceback (most recent call last):
  File "C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\ComfyUI-ImageReward\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\ComfyUI-ImageReward\nodes.py", line 1, in <module>
    import ImageReward as RM
  File "C:\Users\nicol\Desktop\Comfy UI Done\python_embeded\Lib\site-packages\ImageReward\__init__.py", line 1, in <module>
    from .utils import *
  File "C:\Users\nicol\Desktop\Comfy UI Done\python_embeded\Lib\site-packages\ImageReward\utils.py", line 19, in <module>
    from .ImageReward import ImageReward
  File "C:\Users\nicol\Desktop\Comfy UI Done\python_embeded\Lib\site-packages\ImageReward\ImageReward.py", line 16, in <module>
    from .models.BLIP.blip_pretrain import BLIP_Pretrain
  File "C:\Users\nicol\Desktop\Comfy UI Done\python_embeded\Lib\site-packages\ImageReward\models\__init__.py", line 1, in <module>
    from .AestheticScore import *
  File "C:\Users\nicol\Desktop\Comfy UI Done\python_embeded\Lib\site-packages\ImageReward\models\AestheticScore.py", line 16, in <module>
    import clip
ModuleNotFoundError: No module named 'clip'

Cannot import C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\ComfyUI-ImageReward module for custom nodes: No module named 'clip'

And module Clip dosen't exsist inside the embeded python in comfy ui

**Comment by imchkkim** [comment]
I had same problem (on windows 11) 


```
clip @ git+https://github.com/openai/CLIP.git
```

Adding the line above to requirements.txt. problem solved.

**Comment by ZaneA** [comment]
Thanks for the bug report and solution, I've added this to the `requirements.txt` now :)
